In [1]:
## Write a Python program to multiply a 𝑀 × 𝑁 matrix by 𝑁 × 𝐴 matrix and
#create a real matrix product.

import numpy as np
M = np.random.random((5,3))
print("First array:")
print(M)
print("---------------")
N = np.random.random((3,2))
print("Second array:")
print(N)
print('----------------')
A = np.dot(M,N)
print("Dot product of two arrays:")
print(A)

First array:
[[8.08159737e-01 5.52191371e-01 2.04390378e-04]
 [7.74176121e-01 2.39173352e-01 6.64829405e-01]
 [1.71575072e-01 8.94913840e-01 8.73119544e-01]
 [2.67939702e-02 7.91266714e-01 9.21924134e-01]
 [8.03745936e-01 2.64488599e-01 5.12674382e-01]]
---------------
Second array:
[[0.91741851 0.05327961]
 [0.7225952  0.71132591]
 [0.57465454 0.18432741]]
----------------
Dot product of two arrays:
[[1.14054899 0.43588414]
 [1.26511626 0.33392428]
 [1.3058087  0.80665672]
 [1.1261347  0.73421198]
 [1.22310025 0.3254608 ]]


In [2]:
#Write a NumPy program to check if each element of an array of your choice is
#composed of digits, lower case letters, and upper case letters only.

import numpy as np
x = np.array(['Python' ,'PHP' ,'JS' , 'Examples' , 'html5' , '5'], dtype=np.str)
print("\nOriginal Array:")
print(x)
s1 = np.char.isdigit(x)
s2 = np.char.islower(x)
s3 = np.char.isupper(x)

print("Digit only       =",s1)
print("Lower cases only =",s2)
print("Upper cases only =",s3)




Original Array:
['Python' 'PHP' 'JS' 'Examples' 'html5' '5']
Digit only       = [False False False False False  True]
Lower cases only = [False False False False  True False]
Upper cases only = [False  True  True False False False]


C:\Users\suraj\AppData\Local\Temp\ipykernel_4528\967194723.py:5: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.array(['Python' ,'PHP' ,'JS' , 'Examples' , 'html5' , '5'], dtype=np.str)


In [ ]:
## 3: Write a program that reads two space-separated positive integers 𝑋 and
## 𝑌 as input and perform the following tasks:

import numpy as np
X = input("Enter two values:").split()
Y = input("Enter two values:").split()
print(X)
print(Y,'\n')
lst1 = int(input(np.arange(0,112,7)))
lst2 = int(input(np.arange(0,144,9)))
print(lst1)
print(lst2,'\n')
np1 = np.array(lst1.reshape(4,4))
np2 = np.array(lst2.reshape(4,4))
print(np1)
print(np2,'\n')
np3 = np1-np2
print(np3,end="")
print(np3.reshape(1,16))

Enter two values:7
Enter two values:9
['7']
['9'] 

[  0   7  14  21  28  35  42  49  56  63  70  77  84  91  98 105]7


In [5]:
##4: Write a Python program that takes two integer-NumPy arrays, 𝑃 and 𝑄 of
## shape [3 ∗ 3] and perform the following task:

import numpy as np
P = np.array(3 * 3)
Q = np.array(3 * 3)
print("Original arrays:")
print(P)
print(Q)

np.arange(3 * 3).reshape(3,3)

Original arrays:
9
9


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])